# Generated by Django 5.2.2 on 2025-06-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название встречи"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание встречи"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата встречи")),
                ("start_time", models.TimeField(verbose_name="Время начала встречи")),
                ("end_time", models.TimeField(verbose_name="Время окончания встречи")),
                (
                    "organizer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Организатор встречи",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="meetings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Участники встречи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
                "ordering": ["-date", "start_time"],
            },
        ),
    ]
